structure(list(url = "https://api.twitter.com/2/users/by?usernames=icahdq%2CPOTUS%2ChadleywickhaM%2C_R_Foundation%2Cadljfhjsd", 
    status_code = 200L, headers = structure(list(date = "Tue, 02 Nov 2021 20:37:27 UTC", 
        server = "tsa_o", `api-version` = "2.27", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "353", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "900", `x-rate-limit-reset` = "1635886347", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "899", 
        `strict-transport-security` = "max-age=631138519", `x-response-time` = "153", 
        `x-connection-hash` = "ebbd90b82704b550bc7da12bfde5c544cde308b0971c01f98f16f6c9d980e06f"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Tue, 02 Nov 2021 20:37:27 UTC", 
            server = "tsa_o", `api-version` = "2.27", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "353", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "900", 
            `x-rate-limit-reset` = "1635886347", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "899", 
            `strict-transport-security` = "max-age=631138519", 
            `x-response-time` = "153", `x-connection-hash` = "ebbd90b82704b550bc7da12bfde5c544cde308b0971c01f98f16f6c9d980e06f"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    ".twitter.com"), flag = c(TRUE, TRUE), path = c("/", "/"), 
        secure = c(TRUE, TRUE), expiration = structure(c(1698938349, 
        1698938349), class = c("POSIXct", "POSIXt")), name = c("personalization_id", 
        "guest_id"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"data\":[{\"id\":\"31560768\",\"name\":\"International Communication Association\",\"username\":\"icahdq\"},{\"id\":\"1349149096909668363\",\"name\":\"President Biden\",\"username\":\"POTUS\"},{\"id\":\"69133574\",\"name\":\"Hadley Wickham\",\"username\":\"hadleywickham\"},{\"id\":\"794458165987438592\",\"name\":\"The R Foundation\",\"username\":\"_R_Foundation\"}],\"errors\":[{\"value\":\"adljfhjsd\",\"detail\":\"Could not find user with usernames: [adljfhjsd].\",\"title\":\"Not Found Error\",\"resource_type\":\"user\",\"parameter\":\"usernames\",\"resource_id\":\"adljfhjsd\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"}]}"), 
    date = structure(1635885447, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.023172, 
    connect = 0.037088, pretransfer = 0.058144, starttransfer = 0.237719, 
    total = 0.23788)), class = "response")
