structure(list(url = "https://api.twitter.com/2/tweets?tweet.fields=attachments%2Cauthor_id%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Cpossibly_sensitive%2Creferenced_tweets%2Csource%2Ctext%2Cwithheld&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&expansions=author_id%2Centities.mentions.username%2Cgeo.place_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id&place.fields=contained_within%2Ccountry%2Ccountry_code%2Cfull_name%2Cgeo%2Cid%2Cname%2Cplace_type&ids=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12%2C13%2C14%2C15", 
    status_code = 200L, headers = structure(list(date = "Sun, 19 Dec 2021 20:49:25 UTC", 
        server = "tsa_o", `api-version` = "2.32", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "325", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "300", `x-rate-limit-reset` = "1639947531", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "261", 
        `strict-transport-security` = "max-age=631138519", `x-response-time` = "139", 
        `x-connection-hash` = "a8dd0b91b56c071e60ae4b83ca064c192d64678a1e03c31011044170217df8ed"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Sun, 19 Dec 2021 20:49:25 UTC", 
            server = "tsa_o", `api-version` = "2.32", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "325", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "300", 
            `x-rate-limit-reset` = "1639947531", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "261", 
            `strict-transport-security` = "max-age=631138519", 
            `x-response-time` = "139", `x-connection-hash` = "a8dd0b91b56c071e60ae4b83ca064c192d64678a1e03c31011044170217df8ed"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    ".twitter.com", ".twitter.com", ".twitter.com"), flag = c(TRUE, 
    TRUE, TRUE, TRUE), path = c("/", "/", "/", "/"), secure = c(TRUE, 
    TRUE, TRUE, TRUE), expiration = structure(c(1702744284, 1702744284, 
    1702744284, 1702744284), class = c("POSIXct", "POSIXt")), 
        name = c("guest_id_marketing", "guest_id_ads", "personalization_id", 
        "guest_id"), value = c("REDACTED", "REDACTED", "REDACTED", 
        "REDACTED")), row.names = c(NA, -4L), class = "data.frame"), 
    content = charToRaw("{\"errors\":[{\"value\":\"1\",\"detail\":\"Could not find tweet with ids: [1].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"1\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"2\",\"detail\":\"Could not find tweet with ids: [2].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"2\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"3\",\"detail\":\"Could not find tweet with ids: [3].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"3\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"4\",\"detail\":\"Could not find tweet with ids: [4].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"4\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"5\",\"detail\":\"Could not find tweet with ids: [5].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"5\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"6\",\"detail\":\"Could not find tweet with ids: [6].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"6\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"7\",\"detail\":\"Could not find tweet with ids: [7].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"7\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"8\",\"detail\":\"Could not find tweet with ids: [8].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"8\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"9\",\"detail\":\"Could not find tweet with ids: [9].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"9\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"10\",\"detail\":\"Could not find tweet with ids: [10].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"10\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"11\",\"detail\":\"Could not find tweet with ids: [11].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"11\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"12\",\"detail\":\"Could not find tweet with ids: [12].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"12\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"13\",\"detail\":\"Could not find tweet with ids: [13].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"13\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"14\",\"detail\":\"Could not find tweet with ids: [14].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"14\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"},{\"value\":\"15\",\"detail\":\"Could not find tweet with ids: [15].\",\"title\":\"Not Found Error\",\"resource_type\":\"tweet\",\"parameter\":\"ids\",\"resource_id\":\"15\",\"type\":\"https://api.twitter.com/2/problems/resource-not-found\"}]}"), 
    date = structure(1639946965, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.1e-05, 
    connect = 3.2e-05, pretransfer = 0.000128, starttransfer = 0.152865, 
    total = 0.153075)), class = "response")
