structure(list(url = "https://api.twitter.com/2/users?ids=NA%2CNA%2CNA&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld", 
    status_code = 400L, headers = structure(list(date = "Sun, 04 Jul 2021 12:22:58 UTC", 
        server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "221", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "900", `x-rate-limit-reset` = "1625402278", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "899", 
        `strict-transport-security` = "max-age=631138519", `x-connection-hash` = "358099e7ee27d3f1daf675083a1379c26cfd5d6955da63ec8b1cae9cb6b5f130"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/2", 
        headers = structure(list(date = "Sun, 04 Jul 2021 12:22:58 UTC", 
            server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "221", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "900", 
            `x-rate-limit-reset` = "1625402278", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "899", 
            `strict-transport-security` = "max-age=631138519", 
            `x-connection-hash` = "358099e7ee27d3f1daf675083a1379c26cfd5d6955da63ec8b1cae9cb6b5f130"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    ".twitter.com"), flag = c(TRUE, TRUE), path = c("/", "/"), 
        secure = c(TRUE, TRUE), expiration = structure(c(1688456705, 
        1688456705), class = c("POSIXct", "POSIXt")), name = c("personalization_id", 
        "guest_id"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"errors\":[{\"parameters\":{\"ids\":[\"NA,NA,NA\"]},\"message\":\"The `ids` query parameter value [NA] does not match ^[0-9]{1,19}$\"}],\"title\":\"Invalid Request\",\"detail\":\"One or more parameters to your request was invalid.\",\"type\":\"https://api.twitter.com/2/problems/invalid-request\"}"), 
    date = structure(1625401378, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.029738, 
    connect = 0.043284, pretransfer = 0.090444, starttransfer = 0.221434, 
    total = 0.221575)), class = "response")
