structure(list(url = "https://api.twitter.com/2/tweets/1399020950369226755/liking_users?user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld", 
    status_code = 200L, headers = structure(list(date = "Sat, 19 Jun 2021 13:26:22 UTC", 
        server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "53", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "75", `x-rate-limit-reset` = "1624110071", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "65", 
        `strict-transport-security` = "max-age=631138519", `x-connection-hash` = "6e99841bc07c3ff86c28aac8a8e7b0de35b600a766dc48fe9c37c8d02f83813d"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Sat, 19 Jun 2021 13:26:22 UTC", 
            server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "53", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "75", 
            `x-rate-limit-reset` = "1624110071", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "65", 
            `strict-transport-security` = "max-age=631138519", 
            `x-connection-hash` = "6e99841bc07c3ff86c28aac8a8e7b0de35b600a766dc48fe9c37c8d02f83813d"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    ".twitter.com"), flag = c(TRUE, TRUE), path = c("/", "/"), 
        secure = c(TRUE, TRUE), expiration = structure(c(1687174738, 
        1687174738), class = c("POSIXct", "POSIXt")), name = c("personalization_id", 
        "guest_id"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"meta\":{\"result_count\":0}}"), 
    date = structure(1624109182, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 6.4e-05, 
    connect = 6.7e-05, pretransfer = 0.000243, starttransfer = 0.181274, 
    total = 0.18135)), class = "response")
