name: Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Please confirm the following
    description: If you cannot check most of the boxes below, it is probably not a bug. Please consider using [discussions](https://github.com/cjbarrie/academictwitteR/discussions) instead.
    options:
    - label: I have searched the existing issues
      required: true
    - label: The behaviour of the program is deviated from what is described in the documentation.
      required: true
    - label: I can reproduce this problem for more than one time.
      required: true
    - label: "This is NOT a 3-digit error -- it does not display an error message like `something went wrong. Status code: 400.`"
      required: false
    - label: This is a 3-digit error and I have consulted the [Understanding API errors](https://cran.r-project.org/web/packages/academictwitteR/vignettes/academictwitteR-errors.html) vignette and the suggestions do not help.
      required: false
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Please use `reprex::reprex()` to create [an reproducible example](https://reprex.tidyverse.org/), if possible.
    placeholder: |
      paste the output from `reprex::reprex()` here
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: Please run `sessionInfo()` and copy the result here.
    placeholder: |
      paste the output from `sessionInfo()` here
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

  validations:
    required: false
