structure(list(url = "https://api.twitter.com/2/users/17880989/mentions?max_results=100&start_time=2021-05-30T14%3A12%3A24.000Z&end_time=2021-06-02T21%3A15%3A24.000Z&tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Cpossibly_sensitive%2Creferenced_tweets%2Csource%2Ctext%2Cwithheld&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&expansions=author_id%2Centities.mentions.username%2Cgeo.place_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id&place.fields=contained_within%2Ccountry%2Ccountry_code%2Cfull_name%2Cgeo%2Cid%2Cname%2Cplace_type", 
    status_code = 200L, headers = structure(list(date = "Fri, 03 Jun 2022 10:54:09 UTC", 
        server = "tsa_o", `api-version` = "2.43", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "53", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "450", `x-rate-limit-reset` = "1654254458", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "442", 
        `strict-transport-security` = "max-age=631138519", `x-response-time` = "155", 
        `x-connection-hash` = "222be9f80ba17e0edaa9b9922d0e14d3ed65a022abea2f4ce5b0113abb4c0e4e"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Fri, 03 Jun 2022 10:54:09 UTC", 
            server = "tsa_o", `api-version` = "2.43", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "53", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "450", 
            `x-rate-limit-reset` = "1654254458", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "442", 
            `strict-transport-security` = "max-age=631138519", 
            `x-response-time` = "155", `x-connection-hash` = "222be9f80ba17e0edaa9b9922d0e14d3ed65a022abea2f4ce5b0113abb4c0e4e"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = ".twitter.com", 
        flag = TRUE, path = "/", secure = TRUE, expiration = structure(1688467960, class = c("POSIXct", 
        "POSIXt")), name = "guest_id", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"meta\":{\"result_count\":0}}"), 
    date = structure(1654253649, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.1e-05, 
    connect = 5.2e-05, pretransfer = 0.000108, starttransfer = 0.235762, 
    total = 0.235874)), class = "response")
