structure(list(url = "https://api.twitter.com/2/tweets/1399797349296197635/retweeted_by?tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Cpossibly_sensitive%2Creferenced_tweets%2Csource%2Ctext%2Cwithheld&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld", 
    status_code = 200L, headers = structure(list(date = "Wed, 09 Feb 2022 12:05:06 UTC", 
        server = "tsa_o", `api-version` = "2.36", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "53", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "75", `x-rate-limit-reset` = "1644408607", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "67", 
        `strict-transport-security` = "max-age=631138519", `x-response-time` = "156", 
        `x-connection-hash` = "42b57a19a72b7987c16fb056ea39ed77cbfa0d177e2cfe58a2a337beaf68b3fb"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 09 Feb 2022 12:05:06 UTC", 
            server = "tsa_o", `api-version` = "2.36", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "53", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "75", 
            `x-rate-limit-reset` = "1644408607", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "67", 
            `strict-transport-security` = "max-age=631138519", 
            `x-response-time` = "156", `x-connection-hash` = "42b57a19a72b7987c16fb056ea39ed77cbfa0d177e2cfe58a2a337beaf68b3fb"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = ".twitter.com", 
        flag = TRUE, path = "/", secure = TRUE, expiration = structure(1678622683, class = c("POSIXct", 
        "POSIXt")), name = "guest_id", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"meta\":{\"result_count\":0}}"), 
    date = structure(1644408306, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.6e-05, 
    connect = 2.6e-05, pretransfer = 0.000107, starttransfer = 0.170269, 
    total = 0.17038)), class = "response")
