structure(list(url = "https://api.twitter.com/2/users/1145936974064177152/followers?max_results=1000&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&pagination_token=7CC81IB6HQ5HCZZZ", 
    status_code = 200L, headers = structure(list(date = "Sun, 04 Jul 2021 12:25:10 UTC", 
        server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "89", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "15", `x-rate-limit-reset` = "1625402279", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "10", 
        `strict-transport-security` = "max-age=631138519", `x-connection-hash` = "358099e7ee27d3f1daf675083a1379c26cfd5d6955da63ec8b1cae9cb6b5f130"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Sun, 04 Jul 2021 12:25:10 UTC", 
            server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "89", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "15", 
            `x-rate-limit-reset` = "1625402279", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "10", 
            `strict-transport-security` = "max-age=631138519", 
            `x-connection-hash` = "358099e7ee27d3f1daf675083a1379c26cfd5d6955da63ec8b1cae9cb6b5f130"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    ".twitter.com"), flag = c(TRUE, TRUE), path = c("/", "/"), 
        secure = c(TRUE, TRUE), expiration = structure(c(1688456705, 
        1688456705), class = c("POSIXct", "POSIXt")), name = c("personalization_id", 
        "guest_id"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"meta\":{\"result_count\":0,\"previous_token\":\"ONJNUDKPE5QEIZZZ\"}}"), 
    date = structure(1625401510, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 9.8e-05, 
    connect = 0.000102, pretransfer = 0.000381, starttransfer = 0.400639, 
    total = 0.40076)), class = "response")
