structure(list(url = "https://api.twitter.com/2/tweets/1400199391961620488/liking_users?user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld", 
    status_code = 200L, headers = structure(list(date = "Sat, 19 Jun 2021 11:52:28 UTC", 
        server = "tsa_o", `set-cookie` = "REDACTED", `set-cookie` = "REDACTED", 
        `content-type` = "application/json; charset=utf-8", `cache-control` = "no-cache, no-store, max-age=0", 
        `content-length` = "53", `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "75", `x-rate-limit-reset` = "1624104295", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "73", 
        `strict-transport-security` = "max-age=631138519", `x-connection-hash` = "d7ef43239fd2282da03f2055694b919c3df8a4dcf582e5c38a3d170d2f12a77d"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Sat, 19 Jun 2021 11:52:28 UTC", 
            server = "tsa_o", `set-cookie` = "REDACTED", `set-cookie` = "REDACTED", 
            `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "53", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "75", 
            `x-rate-limit-reset` = "1624104295", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "73", 
            `strict-transport-security` = "max-age=631138519", 
            `x-connection-hash` = "d7ef43239fd2282da03f2055694b919c3df8a4dcf582e5c38a3d170d2f12a77d"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    ".twitter.com"), flag = c(TRUE, TRUE), path = c("/", "/"), 
        secure = c(TRUE, TRUE), expiration = structure(c(1687175548, 
        1687175548), class = c("POSIXct", "POSIXt")), name = c("personalization_id", 
        "guest_id"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"meta\":{\"result_count\":0}}"), 
    date = structure(1624103548, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.0473, 
    connect = 0.063542, pretransfer = 0.139533, starttransfer = 0.296393, 
    total = 0.296571)), class = "response")
