structure(list(url = "https://api.twitter.com/2/tweets/1476155918597373952/retweeted_by?tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Cpossibly_sensitive%2Creferenced_tweets%2Csource%2Ctext%2Cwithheld&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&pagination_token=7140dibdnow9c7btw480xmriyhusgmvg397gkj1jyjf3k", 
    status_code = 200L, headers = structure(list(date = "Wed, 09 Feb 2022 12:55:19 UTC", 
        server = "tsa_o", `api-version` = "2.36", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "114", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "75", `x-rate-limit-reset` = "1644412214", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "72", 
        `strict-transport-security` = "max-age=631138519", `x-response-time` = "158", 
        `x-connection-hash` = "4d56913fe5da1cac9e2f79efe41da57a3ae6e8de06641503bfa2607561dbd2c3"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Wed, 09 Feb 2022 12:55:19 UTC", 
            server = "tsa_o", `api-version` = "2.36", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "114", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "75", 
            `x-rate-limit-reset` = "1644412214", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "72", 
            `strict-transport-security` = "max-age=631138519", 
            `x-response-time` = "158", `x-connection-hash` = "4d56913fe5da1cac9e2f79efe41da57a3ae6e8de06641503bfa2607561dbd2c3"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = ".twitter.com", 
        flag = TRUE, path = "/", secure = TRUE, expiration = structure(1678622683, class = c("POSIXct", 
        "POSIXt")), name = "guest_id", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"meta\":{\"result_count\":0,\"previous_token\":\"77qpymm88g5h9vqkluxce29vphzsb6kd3lmsibwvsz2nt\"}}"), 
    date = structure(1644411319, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.9e-05, 
    connect = 4e-05, pretransfer = 0.000141, starttransfer = 0.173932, 
    total = 0.174087)), class = "response")
