structure(list(url = "https://api.twitter.com/2/tweets/search/all?query=%23standwithhongkong&max_results=500&start_time=2020-06-20T00%3A00%3A00Z&end_time=2020-06-21T00%3A00%3A00Z&tweet.fields=attachments%2Cauthor_id%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Cpossibly_sensitive%2Creferenced_tweets%2Csource%2Ctext%2Cwithheld&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&expansions=author_id%2Centities.mentions.username%2Cgeo.place_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id&place.fields=contained_within%2Ccountry%2Ccountry_code%2Cfull_name%2Cgeo%2Cid%2Cname%2Cplace_type&q=%23CPC100Years", 
    status_code = 401L, headers = structure(list(date = "Sun, 04 Jul 2021 13:14:24 UTC", 
        server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "91", 
        `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
        `x-xss-protection` = "0", `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `strict-transport-security` = "max-age=631138519", 
        `x-connection-hash` = "cf5ec88fb71130f8e692029e90502ae4a86a4ca038611670dd0f5955841268e9"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/2", 
        headers = structure(list(date = "Sun, 04 Jul 2021 13:14:24 UTC", 
            server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "91", `x-frame-options` = "SAMEORIGIN", 
            `content-encoding` = "gzip", `x-xss-protection` = "0", 
            `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `strict-transport-security` = "max-age=631138519", 
            `x-connection-hash` = "cf5ec88fb71130f8e692029e90502ae4a86a4ca038611670dd0f5955841268e9"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    ".twitter.com"), flag = c(TRUE, TRUE), path = c("/", "/"), 
        secure = c(TRUE, TRUE), expiration = structure(c(1688456705, 
        1688456705), class = c("POSIXct", "POSIXt")), name = c("personalization_id", 
        "guest_id"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"title\":\"Unauthorized\",\"type\":\"about:blank\",\"status\":401,\"detail\":\"Unauthorized\"}"), 
    date = structure(1625404464, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.4e-05, 
    connect = 4.6e-05, pretransfer = 0.000186, starttransfer = 0.125812, 
    total = 0.125846)), class = "response")
