structure(list(url = "https://api.twitter.com/2/tweets/search/all?query=%23Figliuolo%20lang%3Ait&max_results=500&start_time=2020-12-01T00%3A00%3A00Z&end_time=2020-12-31T00%3A00%3A00Z&tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Cpossibly_sensitive%2Creferenced_tweets%2Csource%2Ctext%2Cwithheld&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&expansions=author_id%2Centities.mentions.username%2Cgeo.place_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id&place.fields=contained_within%2Ccountry%2Ccountry_code%2Cfull_name%2Cgeo%2Cid%2Cname%2Cplace_type", 
    status_code = 200L, headers = structure(list(date = "Sat, 12 Jun 2021 10:34:24 UTC", 
        server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
        `cache-control` = "no-cache, no-store, max-age=0", `content-length` = "53", 
        `x-access-level` = "read", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip", `x-xss-protection` = "0", 
        `x-rate-limit-limit` = "300", `x-rate-limit-reset` = "1623494907", 
        `content-disposition` = "attachment; filename=json.json", 
        `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "298", 
        `strict-transport-security` = "max-age=631138519", `x-connection-hash` = "701bd779d33926d544998aedfad62fa5964ccd1acb582127988e0cd5e055563b"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(date = "Sat, 12 Jun 2021 10:34:24 UTC", 
            server = "tsa_o", `content-type` = "application/json; charset=utf-8", 
            `cache-control` = "no-cache, no-store, max-age=0", 
            `content-length` = "53", `x-access-level` = "read", 
            `x-frame-options` = "SAMEORIGIN", `content-encoding` = "gzip", 
            `x-xss-protection` = "0", `x-rate-limit-limit` = "300", 
            `x-rate-limit-reset` = "1623494907", `content-disposition` = "attachment; filename=json.json", 
            `x-content-type-options` = "nosniff", `x-rate-limit-remaining` = "298", 
            `strict-transport-security` = "max-age=631138519", 
            `x-connection-hash` = "701bd779d33926d544998aedfad62fa5964ccd1acb582127988e0cd5e055563b"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".twitter.com", 
    ".twitter.com"), flag = c(TRUE, TRUE), path = c("/", "/"), 
        secure = c(TRUE, TRUE), expiration = structure(c(1686566007, 
        1686566007), class = c("POSIXct", "POSIXt")), name = c("personalization_id", 
        "guest_id"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"meta\":{\"result_count\":0}}"), 
    date = structure(1623494064, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.8e-05, 
    connect = 2.9e-05, pretransfer = 0.000116, starttransfer = 0.140711, 
    total = 0.14081)), class = "response")
